:nokotlin:
AntiCrustLicensingInitiative/BeeResourceful pull request #1
Opened 2020-01-25 23:40 UTC by Devan-Kerman

:tiny_potato:

2020-01-25 23:42 UTC, 2xsaiko commented
Code size increases by more than 2x but no functionality added

2020-01-25 23:48 UTC, Devan-Kerman commented
perfectly java, as all programs should be

2020-01-26 09:03 UTC, quat1024 commented on src/main/java/com/martmists/beeresourceful/nectars/Vanilla.java
> +	}
cringe

2020-01-26 09:03 UTC, quat1024 commented on src/main/java/com/martmists/beeresourceful/nectars/compat/MobZ.java
> + * Decompiled with CFR 0.148.
cringe 2

2020-01-26 23:41 UTC, Devan-Kerman commented on src/main/java/com/martmists/beeresourceful/nectars/Vanilla.java
> +	}
ohyes

2020-01-26 23:41 UTC, Devan-Kerman commented on src/main/java/com/martmists/beeresourceful/nectars/compat/MobZ.java
> + * Decompiled with CFR 0.148.
ohhhhhhhhyes

2020-05-20 00:32 UTC, i509VCB requested changes

2020-05-20 00:32 UTC, i509VCB commented on src/main/java/com/martmists/beeresourceful/nectars/Vanilla.java
> + */
You were lazy enough to leave in the decompiler header

2020-05-20 00:32 UTC, i509VCB commented on src/main/java/com/martmists/beeresourceful/nectars/Vanilla.java
> +	public final HoneyFlavor getDIAMOND_FLAVOR() {
make the field public

2020-05-20 00:32 UTC, i509VCB commented on src/main/java/com/martmists/beeresourceful/nectars/Vanilla.java
> +	public final HoneyFlavor getEMERALD_FLAVOR() {
make the field public

2020-05-20 00:32 UTC, i509VCB commented on src/main/java/com/martmists/beeresourceful/nectars/Vanilla.java
> +	public final HoneyFlavor getIRON_FLAVOR() {
make the field public

2020-05-20 00:32 UTC, i509VCB commented on src/main/java/com/martmists/beeresourceful/nectars/Vanilla.java
> +	public final HoneyFlavor getGOLD_FLAVOR() {
make the field public

2020-05-20 00:32 UTC, i509VCB commented on src/main/java/com/martmists/beeresourceful/nectars/Vanilla.java
> +	public final HoneyFlavor getLAPIS_FLAVOR() {
make the field public

2020-05-20 00:32 UTC, i509VCB commented on src/main/java/com/martmists/beeresourceful/nectars/Vanilla.java
> +	public final HoneyFlavor getREDSTONE_FLAVOR() {
make the field public

2020-05-20 00:32 UTC, i509VCB commented on src/main/java/com/martmists/beeresourceful/nectars/Vanilla.java
> +	public final HoneyFlavor getGLOWSTONE_FLAVOR() {
make the field public

2020-05-20 00:32 UTC, i509VCB commented on src/main/java/com/martmists/beeresourceful/nectars/Vanilla.java
> +	public final HoneyFlavor getCOAL_FLAVOR() {
make the field public

2020-05-20 00:32 UTC, i509VCB commented on src/main/java/com/martmists/beeresourceful/nectars/Vanilla.java
> +	public final HoneyFlavor getQUARTZ_FLAVOR() {
make the field public

2020-05-20 00:32 UTC, i509VCB commented on src/main/java/com/martmists/beeresourceful/nectars/Vanilla.java
> +	public final HoneyFlavor getXP_FLAVOR() {
make the field public

2020-05-20 00:32 UTC, i509VCB commented on src/main/java/com/martmists/beeresourceful/nectars/Vanilla.java
> +	public final HoneyFlavor getOBSIDIAN_FLAVOR() {
make the field public

2020-05-20 00:32 UTC, i509VCB commented on src/main/java/com/martmists/beeresourceful/nectars/Vanilla.java
> +	public final HoneyFlavor getBLAZE_FLAVOR() {
make the field public

2020-05-20 00:32 UTC, i509VCB commented on src/main/java/com/martmists/beeresourceful/nectars/compat/TechReborn.java
> +	public final HoneyFlavor getRUBBER_FLAVOR() {
make the field public

2020-05-20 00:32 UTC, i509VCB commented on src/main/java/com/martmists/beeresourceful/nectars/compat/TechReborn.java
> +	public final HoneyFlavor getALUMINIUM_FLAVOR() {
make the field public

2020-05-20 00:33 UTC, Devan-Kerman commented on src/main/java/com/martmists/beeresourceful/nectars/Vanilla.java
> + */
e

2020-05-20 08:12 UTC, natanfudge commented on src/main/java/com/martmists/beeresourceful/nectars/compat/TechReborn.java
> +	public final HoneyFlavor getALUMINIUM_FLAVOR() {
Make the field public

2021-04-18 00:36 UTC, closed without merging